name: Build the new code and Test with cukinia

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install gdown
        run: pip install gdown

      - name: Setup ARM target container
        run: ./setup_container.sh

      - name: Download toolchain gcc, build code and upload to target container
        run: ./compile_upload.sh

      - name: Run unit & cukinia tests and get results
        run: ./test_sequence.sh

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test_logs
          path: test_logs/
